object Versions {
    const val CORE_KTX = "1.7.0"
    const val APPCOMPAT = "1.4.0"
    const val CONSTRAINT_LAYOUT = "2.1.4"
    const val GRADLE = "7.2.0"
    const val KOTLIN = "1.6.10"
    const val HILT = "2.40"
    const val HILT_COMPILER = "1.0.0"
    const val MATERIAL = "1.6.1"
    const val JAVA = "11"
    const val LIFECYCLE = "2.4.0"
    const val ACTIVITY_LIFECYCLE = "1.4.0"
    const val RETROFIT = "2.9.0"
    const val RETROFIT_CONVERTER = "0.8.0"
    const val OKHTTP_LOGGING = "5.0.0-alpha.6"
    const val LOTTIE = "4.1.0"
    const val SERIALIZATION_CONVERTER = "0.8.0"
    const val SERIALIZATION_JSON = "1.2.1"
}
